{% set name = "biobear" %}
{% set version = "0.23.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/biobear-{{ version }}.tar.gz
  sha256: 200ce4f40bbdfffdb355764052365d4e3fbbede8e76c124aeb23b0a5104a235c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - maturin >=1.1.0,<2.0.0                 # [build_platform != target_platform]
  host:
    - python
    - maturin >=1.1.0,<2.0.0
    - pip
    - xz
  run:
    - python
    - pyarrow >=12
test:
  imports:
    - biobear
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wheretrue/biobear
  summary: biobear is a Python library designed for processing scientific data with Rust and Arrow.
  description: biobear is a Python library designed for reading and searching bioinformatic file formats, using Rust as its backend and producing Arrow Batch Readers and other downstream formats (like polars or duckdb).
  license: MIT
  license_file: LICENSE
  license_family: MIT
  doc_url: https://www.wheretrue.dev/docs/exon/biobear/
  dev_url: https://github.com/wheretrue/biobear

extra:
  recipe-maintainers:
    - tshauck
